dist: ./bin
builds:
  - binary: yak
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
     - LICENSE
     - README.md
     - static/completions/*
nfpms:
  - description: A tool to log in to AWS through Okta
    maintainer: Redbubble <domain@redbubble.com>
    formats:
      - deb
      - rpm
    license: MIT
    contents:
      - src: "static/completions/yak.zsh"
        dst : "/usr/share/zsh/vendor-completions/_yak"
      - src: "static/completions/yak.bash"
        dst: "/usr/share/bash-completion/completions/yak"
brews:
  - tap:
      owner: redbubble
      name: homebrew-yak
    commit_author:
      name: Redbubble Delivery Engineering Team
      email: delivery-engineers@redbubble.com

    folder: Formula
    homepage: https://github.com/redbubble/yak
    description: A tool to log in to AWS through Okta
    dependencies:
      - name: pinentry-mac

    test: |
      system "#{bin}/yak --help"
    install: |
      bin.install "yak"
      bash_completion.install "static/completions/yak.bash" => "yak"
      zsh_completion.install "static/completions/yak.zsh" => "_yak"
