language: go
go:
  - 1.x
before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_e668e8769cda_key -iv $encrypted_e668e8769cda_iv -in travis-ci.enc -out travis-ci -d
  - chmod 600 travis-ci
  - ssh-add travis-ci
install:
  - go get github.com/redbubble/go-passe
  - go get github.com/golang/dep/cmd/dep
  - make vendor
script:
  - make test
  - make build
deploy:
  provider: releases
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tag: release-*
