[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.32"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[prune]
  go-tests = true
  unused-packages = true
